### ISSUE TITLE
CRC calculation differences

### ISSUE THREAD

**Issue by roysaad** [b48736/axpert-monitor#8]
Hello, 
Thank you for this amazing project. It really helped me integrate my solar inverter to my home automation system.
While trying some custom commands (Mainly QEDYYYYMMDD to get the PV production), I noticed that they were failing on some days while working on others, although they worked using another [project](https://github.com/jblance/mpp-solar) by @jblance.
Digging deeper, I found that he was using a different CRC function (written in python). So I translated his function to javascript and replaced it in your CRC.js file. It seems the CRC calculations are now more stable and there's no need for the POP02 exception.
I created a pull request #7 for you to consider.

Thanks again for your work.

**Comment by b48736** [comment]
Fixed in version 1.0.1, merged in PR: #9 
Thanks!
